# Reproducibility

by Xindi (Cindy) Hu

Our lab adopts the following practices to maximize the reproducibility of our work. 

1. Design studies with appropriate methodology and adherence to best practices in environmental health, epidemiology, and biostatistics
2. Create reproducible workflows
3. Process and analyze data with internal replication and masking
4. Use reporting checklists with manuscripts
5. Publish preprints
6. Publish data (when possible) and replication scripts


## What is the reproducibility crisis? 

In the past decade, an increasing number of studies have found that published study findings could not be reproduced. Researchers found that it was not possible to reproduce estimates from published studies: 1) with the same data and same or similar code and 2) with newly collected data using the same (or similar) study design. These "failures" of reproducibility were frequent enough and broad enough in scope, occurring across a range of disciplines (epidemiology, psychology, economics, and others) to be deeply troubling. Program and policy decisions based on erroneous research findings could lead to wasted resources, and at worst, could harm intended beneficiaries. This crisis has motivated new practices in reproducibility, transparency, and openness. Our lab is committed to adopting these best practices, and much of the remainder of the lab manual focuses on how to do so. 

Recommended readings on the "reproducibility crisis": 

- Nuzzo R. How scientists fool themselves – and how they can stop. 2015. [https://www.nature.com/articles/526182a]()

- Stoddart C. Is there a reproducibility crisis in science? 2016. [https://www.nature.com/articles/d41586-019-00067-3](https://www.nature.com/articles/d41586-019-00067-3)

- Munafo MR, et al. A manifesto for reproducible science. *Nature Human Behavior* 2017 [http://dx.doi.org/10.1038/s41562-016-0021](http://dx.doi.org/10.1038/s41562-016-0021)


## Study design

Appropriate study design is beyond the scope of this lab manual and is something trainees develop through their coursework and mentoring.

## Create reproducible workflows

Reproducible workflows allow a user to reproduce study estimates and ideally figures and tables with a "single click". In practice, this typically means running replication scripts that complete data processing, data analysis, and figure/table generation. The following chapters provide detailed guidance on this topic: 

- Chapter 4: Code repositories
- Chapter 5: Coding practices
- Chapter 6: Coding style
- Chapter 7: Working with big data
- Chapter 9: Github
- Chapter 10: Unix
- Chapter 12: Code publication

## Use reporting checklists with manuscripts

Using reporting checklists helps ensure that peer-reviewed articles contain the information needed for readers to assess the validity of your work and/or attempt to reproduce it. A collection of reporting checklists is available here: [https://www.equator-network.org/about-us/what-is-a-reporting-guideline/)](https://www.equator-network.org/about-us/what-is-a-reporting-guideline/)

## Publish preprints

A preprint is a scientific manuscript that has not been peer reviewed. Preprint servers create digital object identifiers (DOIs) and can be cited in other articles and in grant applications. Because the peer review process can take many months, publishing preprints prior to or during peer review enables other scientists to immediately learn from and build on your work. Importantly, NIH allows applicants to include preprint citations in their biosketches. In most cases, we publish preprints on [medRxiv](https://www.medrxiv.org/).

## Publish data (when possible) and replication scripts

Publishing data and replication scripts allows other scientists to reproduce your work, access replication datasets, and to build upon it. We typically publish data on the [Harvard Dataverse](https://dataverse.harvard.edu/) and share links to and archive code in [Github](github.com) repositories. (Note: A Harvard affiliation is not required to access or store data in the Harvard Dataverse - you can even transfer account ownership to other email addresses after you leave an institution.)
